### ISSUE TITLE
PR로 참여하였는데 번역자에는 한분만 올라가계시네요.

### ISSUE THREAD

**Issue by jinto** [aikorea/cs231n#63]
최종 번역을 보니, 전혀 참고를 안하고 번역하신 것 같습니다만, 의미있는 PR이었다면 번역 참여자에 언급해주세요.

**Comment by jinto** [comment]
이 이슈는 무시하시죠. 별로 상관도 없는데, 결과물보고 기분이 상해서 이슈를 만들었네요.
제가 많은 부분을 번역을 많이 한것도 아니고, 제이름은 언급하지 말아주세요.
하지만, 다음번에 비슷한 작업을 진행하신다면 PR올린 사람이 있다면, 그 시도만으로도 최종 결과물에 언급되는 것이 맞는것 같다는 의견을 말씀드립니다.
그럼.

**Comment by myungsub** [comment]
네 앞으로는 꼭 그렇게 하도록 하겠습니다. 기분 상하게 하여 죄송합니다.
